name: artemis_work_planner
description: A work planning and management module for corporate and entrepreneurial endeavors
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.0.0
  sembast: ^3.7.2
  sembast_web: ^2.2.0+1
  path_provider: ^2.1.0
  http: ^1.1.0
  flutter_secure_storage: ^9.2.4
  rummel_blue_theme:
    git:
      url: https://github.com/rummel-tech/resources.git
      path: rummel_blue_theme

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
